server:
  port: 8091

block:
  #困难系数
  difficulty: 4
  #服务端口
  p2pport: 7001
  #监听地址
  address: ws://192.168.1.9:7002

logging:
  config: classpath:config/logback-spring.xml
#freedom:
#  loglink:
#    exclude-paths:
#      - /static/**
#      - /error
#    length: 16
#    prefix: config_
